spring:
  application:
    name: elasticsearch #指定服务名
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
  datasource:
    url: jdbc:mysql://localhost:3306/github?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/resources/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.es.entity

logging:
  level:
    com.es.mapper : debug

test1: 123
test2: 345
test3: 456
